# Generated by Django 2.2.5 on 2020-01-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0005_prec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prec',
        ),
    ]
